name = "xugou-backend"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

# 添加定时触发器，每分钟执行一次监控检查
[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "xugou"
database_id = "a48635f7-d1ed-4106-b46a-82cd1a5ba94b"

[version_metadata]
binding = "CF_VERSION_METADATA"
